 # Configurações do CORS da api
cors:
  originPatterns: http://localhost:8080,https://erudio.com.br,http://localhost:3000

spring:
  # Configuração do vscode
  output:
    ansi:
      enabled: always
   # Configurações do Banco de Dados MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot
    username: root
    password: 5959
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configurações de Hibernação
  jpa:
    hibernate:
        ddl-auto: none
  # Para que seja documentado apenas os paths
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true